services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    # environment:
    #   MINIO_ROOT_USER: ROOT_USER
    #   MINIO_ROOT_PASSWORD: ROOT_PASSWORD
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  init-minio:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc admin user add myminio duckdb-local duckdb-local;
      /usr/bin/mc admin policy attach myminio readwrite --user=duckdb-local;
      if /usr/bin/mc ls myminio/duckdb-local > /dev/null 2>&1; then
        /usr/bin/mc rm -r --force myminio/duckdb-local;
      fi;
      if ! /usr/bin/mc ls myminio/duckdb-local > /dev/null 2>&1; then
        /usr/bin/mc mb myminio/duckdb-local;
      fi;
      exit 0;"